 - name: Nginx content
    copy:
       dest: /var/www/html/index.html
       content: |
          <h1> Esta pagina e do servidor: {{ ansible_nodename }} </h1>
          <p> Esta variavel vem do inventario: {{ var_do_inventory }} </p>
          <p> Data Atual {{ ansible_date_time.iso8601 }} </p>
          <p> conteudo da instalacao do nginx: {{ var_nginx }} </p>
          <p> Conteudo da variavel response: {{ response.stdout }} </p>
          <p> Conteudo da variavel "Datacenter" do inventario: {{ datacenter }}
